### ISSUE TITLE
Connecting controller to wifi

### ISSUE THREAD

**Issue by Nohac** [MoonLiightz/magic-home#1]
Hey!

First off, this library looks amazing! I'm looking to upgrade my lighting at home, and can't find any solution that fits my needs, so I'm thinking of DIY-ing it, I like go, so this seems to fit my needs perfectly!

Since I'm new to all of this, I do have a few questions.
Can I use this library without having to use the "Magic Home" app? I've seen a few videos where you have to go through the app in order to connect the controller to wifi. Is it possible to do the setup with this library or any alternative solution without the app?

Also, just to make sure, this library is for controlling [these kind of devices](https://www.aliexpress.com/item/10000046583126.html?spm=a2g0o.detail.1000014.11.d1321ef4AsM7pb&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.14976.202008.0&scm_id=1007.14976.202008.0&scm-url=1007.14976.202008.0&pvid=28a1624e-91c8-403e-b630-d29e4b725cf7&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.14976.202008.0,pvid:28a1624e-91c8-403e-b630-d29e4b725cf7,tpp_buckets:668%230%23131923%230_668%23808%233772%23929_668%23888%233325%231_4976%230%23202008%237_4976%232711%237538%23977_4976%233104%239653%233_4976%234052%2318550%231_4976%233141%239887%235_668%232846%238116%23996_668%232717%237566%23849_668%231000022185%231000066059%230_668%233422%2315392%23476_4452%230%23194213%230_4452%233474%2315675%2380_4452%233098%239599%23479_4452%233564%2316062%23669)?

**Comment by MoonLiightz** [comment]
Hey, I'm glad you like the library.
Yes of course, with this library you can control the linked devices. I have two of them and used this library to control the devices in my home automation. 

I don't think that you can completely do this without the "Magic Home" app to connect the devices to the wifi. The library can't do this and I don't know of any other way to do it without the app. 

You can also have a look at [Tasmota](https://tasmota.github.io/docs/devices/MagicHome-LED-strip-controller/). I guess you can flash it on the devices. Then you don't need the app anymore and can control the devices via MQTT. But this library will no longer work then.

**Comment by Nohac** [comment]
Thanks for the suggestion, but I would prefer to not have to flash any devices.

I did find this library https://github.com/vikstrous/zengge-lightcontrol
The author seems to have reverse engineered what the app does. Unfortunately he have not implemented the one function that I needed which is "set ssid" https://github.com/vikstrous/zengge-lightcontrol/issues/6

If that would work, I could probably use a raspberry pi to connect to the device and use the zengge-lightcontrol library to connect it to my wifi and avoid using the app all together, which would be ideal.
